version: '3'

services:
  turtlebot3-nav:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BASE_IMAGE=${BASE_IMAGE:-ubuntu:20.04}
    container_name: turtlebot3-nav-noetic
    environment:
      - DISPLAY=:1
      - TURTLEBOT3_MODEL=burger
    ports:
      - "6080:6080"  # noVNC web interface
    volumes:
      - ./:/root/catkin_ws/src/turtlebot3-nav-noetic
    restart: unless-stopped
    # Use detected platform or default to amd64
    platform: ${DOCKER_PLATFORM:-linux/amd64}